// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rule1 struct {
	Type                 *String  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule1) Reset()         { *m = Rule1{} }
func (m *Rule1) String() string { return proto.CompactTextString(m) }
func (*Rule1) ProtoMessage()    {}
func (*Rule1) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *Rule1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule1.Unmarshal(m, b)
}
func (m *Rule1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule1.Marshal(b, m, deterministic)
}
func (m *Rule1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule1.Merge(m, src)
}
func (m *Rule1) XXX_Size() int {
	return xxx_messageInfo_Rule1.Size(m)
}
func (m *Rule1) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule1.DiscardUnknown(m)
}

var xxx_messageInfo_Rule1 proto.InternalMessageInfo

func (m *Rule1) GetType() *String {
	if m != nil {
		return m.Type
	}
	return nil
}

type Rule2 struct {
	// Types that are valid to be assigned to OneOf:
	//	*Rule2_Type
	OneOf                isRule2_OneOf `protobuf_oneof:"one_of"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Rule2) Reset()         { *m = Rule2{} }
func (m *Rule2) String() string { return proto.CompactTextString(m) }
func (*Rule2) ProtoMessage()    {}
func (*Rule2) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *Rule2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule2.Unmarshal(m, b)
}
func (m *Rule2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule2.Marshal(b, m, deterministic)
}
func (m *Rule2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule2.Merge(m, src)
}
func (m *Rule2) XXX_Size() int {
	return xxx_messageInfo_Rule2.Size(m)
}
func (m *Rule2) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule2.DiscardUnknown(m)
}

var xxx_messageInfo_Rule2 proto.InternalMessageInfo

type isRule2_OneOf interface {
	isRule2_OneOf()
}

type Rule2_Type struct {
	Type *String `protobuf:"bytes,1,opt,name=type,proto3,oneof"`
}

func (*Rule2_Type) isRule2_OneOf() {}

func (m *Rule2) GetOneOf() isRule2_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Rule2) GetType() *String {
	if x, ok := m.GetOneOf().(*Rule2_Type); ok {
		return x.Type
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Rule2) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Rule2_Type)(nil),
	}
}

type String struct {
	One                  string   `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two                  string   `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{2}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetOne() string {
	if m != nil {
		return m.One
	}
	return ""
}

func (m *String) GetTwo() string {
	if m != nil {
		return m.Two
	}
	return ""
}

var E_Rule1 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Rule1)(nil),
	Field:         999999,
	Name:          "main.rule1",
	Tag:           "bytes,999999,opt,name=rule1",
	Filename:      "type.proto",
}

var E_Rule2 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Rule2)(nil),
	Field:         999998,
	Name:          "main.rule2",
	Tag:           "bytes,999998,opt,name=rule2",
	Filename:      "type.proto",
}

func init() {
	proto.RegisterType((*Rule1)(nil), "main.Rule1")
	proto.RegisterType((*Rule2)(nil), "main.Rule2")
	proto.RegisterType((*String)(nil), "main.String")
	proto.RegisterExtension(E_Rule1)
	proto.RegisterExtension(E_Rule2)
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xa9, 0x2c, 0x48,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x52, 0x48, 0xcf,
	0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17,
	0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0xd4, 0x29, 0x69, 0x72, 0xb1, 0x06, 0x95, 0xe6, 0xa4, 0x1a,
	0x0a, 0x29, 0x70, 0xb1, 0x80, 0xb4, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8, 0x81,
	0xf4, 0xeb, 0x05, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x07, 0x81, 0x65, 0x94, 0x4c, 0x21, 0x4a, 0x8d,
	0x84, 0x94, 0x70, 0x2b, 0xf5, 0x60, 0x80, 0x28, 0x76, 0xe2, 0xe0, 0x62, 0xcb, 0xcf, 0x4b, 0x8d,
	0xcf, 0x4f, 0x53, 0xd2, 0xe1, 0x62, 0x83, 0xc8, 0x09, 0x09, 0x70, 0x31, 0xe7, 0xe7, 0x41, 0xb4,
	0x71, 0x06, 0x81, 0x98, 0x20, 0x91, 0x92, 0xf2, 0x7c, 0x09, 0x26, 0x88, 0x48, 0x49, 0x79, 0xbe,
	0x95, 0x13, 0x17, 0x6b, 0x11, 0xd8, 0x3d, 0xb2, 0x7a, 0x10, 0xb7, 0xeb, 0xc1, 0xdc, 0xae, 0xe7,
	0x96, 0x99, 0x9a, 0x93, 0xe2, 0x5f, 0x50, 0x92, 0x99, 0x9f, 0x57, 0x2c, 0xb1, 0xbf, 0xc5, 0x16,
	0x6c, 0x3b, 0x37, 0xc4, 0x76, 0xb0, 0x1f, 0x82, 0x20, 0x5a, 0x61, 0x66, 0x18, 0x11, 0x32, 0x63,
	0x1f, 0xa6, 0x19, 0x46, 0x10, 0x33, 0x8c, 0x92, 0xd8, 0xc0, 0x5a, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0xc8, 0xef, 0x2a, 0x54, 0x01, 0x00, 0x00,
}
